### ISSUE TITLE
Mixing commands and options

### ISSUE THREAD

**Issue by kieckerjan** [dmulholland/cops#1]
Hi Darren, is there a principled reason why a parser accepts either a command or an argument/option but not both? Say I want to have a program that accepts three different commands (each with their own options) but also a general verbosity flag for all those commands:

```
prg -v cmd1 -abc
prg -v cmd2 -xyz
prg -v cmd3 -f bla.txt
```
There seems to be no way to get this done, or am I missing something? 

Edit: The reason seems to be an explicit `is_first_arg` check.

**Comment by dmulholl** [comment]
Hello, there's no fundamental reason &mdash; currently the library only checks for a command as the first argument to minimise ambiguity, but it could certainly work as you describe.

If you change this line: https://github.com/dmulholl/args/blob/d5ff20e9fcf1e2793da23ed145ac6f74545c5aad/src/args.c#L1204

to:

```c
else if (parser->positional_args->count == 0 && map_get(parser->command_map, arg, (void**)&cmd_parser)) {
```

it should work as you expect.

I'll have a think about whether this is something I want to introduce globally, but in the meantime you should be able to patch the line to get the desired effect.

**Comment by kieckerjan** [comment]
Thanks! I am now considering if this is what I really want for my program. Still, the library explicitly excluding this possibility seems like taking away a degree of freedom that some developers might need. Just my 2 cents. Cheers!
